# Generated by Django 4.1.2 on 2022-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_location', models.CharField(max_length=22)),
                ('measurement_date', models.DateField()),
                ('measurement_time', models.TimeField()),
                ('temperature', models.IntegerField()),
                ('sensor_name', models.TextField()),
                ('model_sensor', models.TextField()),
                ('sensor_group', models.TextField()),
            ],
        ),
    ]
